# Generated by Django 4.2.7 on 2023-11-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_employee_email_alter_employee_forename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
    ]
